admin:
  username: ambrogio
  password: hurrdurr
  token:    rfvklklfklmvlfked
  
database:
  hostname: xxx
  username: xxx
  password: xxx
  database: xxx
  
miscs:
  minify: enable
  cookie: dafuq are u doing? pls stahp
  csrf:   _csrf
