admin:
  username: ambrogio
  password: hurrdurr
  token:    rfvklklfklmvlfked
  
database:
  hostname: localhost
  username: root
  password: kronos
  database: quotone
  
miscs:
  cookie: dafuq are u doing? pls stahp
  csrf:   _csrf
